FS26F4 22:21 #005
feat: repo or not

Last commit: 36b73c5 - GYZEL1 22:20 #004 (87 seconds ago)

diff --git a/comsui b/comsui
--- a/comsui
+++ b/comsui
@@ -15,7 +15,6 @@ fi
 
 comsui() {
   # Test block utility
-  block --die "which git || echo 'Git not found'"
 
   # Check for options
   extended_desc=""
@@ -45,6 +44,8 @@ Usage: comsui [-t][-l] [-c \"custom description\"] [-p] [-s] [-f]"
         ;;
     esac
   done
+
+  block --die "which git || echo 'Git not found'"
 
   # Check if we're in a git repository
   if ! git rev-parse --git-dir >/dev/null 2>&1; then
